### PR TITLE
Fix: user-server can't access proxy-entrypoint in BM proxy environment.

### PR DESCRIPTION
**Pull request by xuezhaojun**
Signed-off-by: xuezhaojun <zxue@redhat.com>

Fixes: https://access.redhat.com/support/cases/#/case/03400011
Fixes: https://issues.redhat.com/browse/ACM-2829

### CODE REVIEW

**Comment by xuezhaojun** [comment]
@xuezhaojun  Need to update backplane-operator as well.

**Comment by xuezhaojun** [comment]
/hold 
Wait for 2.8.

**Comment by qiujian16** [comment]
should this be backported to z stream?

**Comment by xuezhaojun** [comment]
@qiujian16 debug log added, please take another look! Thanks!

**Comment by xuezhaojun** [comment]
/unhold
fast-forward to 2.8(backplane-2.3) is done, now it's safe to unhold the PR.

**Pull request merged**
